# Generated by Django 4.2.1 on 2023-05-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Ingrese una descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Ingrese una descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingrese el nombre', max_length=100)),
                ('apellidos', models.TextField(blank=True, help_text='Ingrese una descripcion')),
                ('documento', models.IntegerField()),
                ('fechanacimiento', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.tipodocumento')),
                ('lugarresidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.ciudad')),
            ],
        ),
    ]
